### PR TITLE
Added instruction to test controllers with Inertia

### PR DESCRIPTION
**Pull request by snake-py**
Today I struggled with creating tests inside my Laravel package. I switched from normal blade rendering to Inertia rendering. I heavily rely on Orchestral/Testbench great lib. I did not find any straightforward docs for doing this. I thought I will add it in case anyone else will struggle with this.

### CODE REVIEW

**Comment by crynobone** [comment]
I don't have issue adding example on how we can add tests for Inertia or Livewire but this feel more suitable to be added as a trait similar to other traits available in Testbench.

I believe the main objective of that trait is to register Inertia view path, right?

**Comment by snake-py** [comment]
@crynobone 

I think the trait's objective would be to register the provider, Viewpath and the FileReader with the correct extensions. I can later submit a trait like this. Also, it would need to be documented that a dummy blade file is required.

**Comment by crynobone** [comment]
> Also, it would need to be documented that a dummy blade file is required.

Submit a PR first, we will review and adjust the usage API from there. One idea is to add the test helpers to `inertiajs/inertia-laravel`.

**Comment by snake-py** [comment]
@crynobone just to clarify, I will submit the PR to https://github.com/orchestral/testbench

**Comment by crynobone** [comment]
https://github.com/orchestral/testbench-core for now

**Pull request closed without merging**
